#!/bin/bash

pushd $HOME/dot
cp -f gitconfig $HOME/.gitconfig
ln -fs dot/bashrc_osx $HOME/.profile
ln -fs dot/vimrc $HOME/.vimrc
ln -fsF dot/vim $HOME/.vim
#ln -fs dot/minttyrc $HOME/.minttyrc
#bin/apt-cyg install vim
#cp bin/apt-cyg /bin
#cp _vimperatorrc "$USERPROFILE"
#cp vimrc "$USERPROFILE/_vimrc"
#cp ahk/altspace.ahk "$USERPROFILE/Start Menu/Programs/Startup/"
#pushd vim
#mkdir -p "$USERPROFILE/vimfiles"
#cp -r * "$USERPROFILE/vimfiles"
#popd
popd
source $HOME/.profile
