alias ls='ls -hF -G'                 # classify files in colour
alias l='ls -Als -G'                              #
PS1='\u@\h:\w$ '

alias more="less -X"
alias b="vi"
export PATH=$PATH:/opt/local/bin
export QTDIR=~/Qt/5.7/clang_64
export PATH=~/development/toolchain/common/bin:$PATH:/usr/local/gcc-arm-none-eabi-4_8-2014q2/bin
alias d="python drone.py"
alias sd="sudo python drone.py"
alias k="cd ~/src/lego"
alias gs="git status"
