#!/bin/bash

# downlad and install karabiner 10.21.0

if [[ -d /Applications/Karabiner.app ]]
then
    echo Karabiner is already installed
    exit 0
fi

curl -o karabiner.dmg https://pqrs.org/osx/karabiner/files/Karabiner-10.21.0.dmg

hdiutil attach karabiner.dmg
open -W /Volumes/Karabiner-10.21.0/Karabiner.sparkle_guided.pkg
hdiutil detach /Volumes/Karabiner-10.21.0
rm karabiner.dmg
